import {test} from 'vitest';import assert from 'node:assert/strict';import {createWorker} from './worker.mjs';
function harness(){const stores=new Map();const calls=[];let offline=false,failInstall=false;const cache=()=>{const map=new Map();return {map,addAll:async urls=>{if(failInstall)throw Error('network');for(const u of urls)map.set(u,new Response('shell:'+u));},match:async(req,opts)=>{const url=typeof req==='string'?req:req.url;return [...map].find(([k])=>opts?.ignoreSearch?k.split('?')[0]===url.split('?')[0]:k===url)?.[1].clone();},put:async(req,r)=>map.set(typeof req==='string'?req:req.url,r),keys:async()=>[...map.keys()],delete:async k=>map.delete(k)};};const env={location:{origin:'https://example.test'},caches:{open:async n=>{if(!stores.has(n))stores.set(n,cache());return stores.get(n);},keys:async()=>[...stores.keys()],delete:async n=>stores.delete(n)},clients:{claim:async()=>calls.push('claim')},fetch:async req=>{calls.push(req.url);if(offline)throw Error('offline');return new Response('network',{status:req.url.includes('missing')?404:200});}};const worker=createWorker(env,{base:'/file-island-echoes/',build:'test',files:['index.html','assets/app.js']});return {worker,env,stores,calls,setOffline:()=>offline=true,fail:()=>failInstall=true};}
const req=(path,options={})=>new Request('https://example.test'+path,options);
test('scope excludes siblings, third parties, POST and partial audio',()=>{const {worker:w}=harness();assert(w.eligible(req('/file-island-echoes/a')));for(const r of [req('/other/a'),new Request('https://github.com/a'),req('/file-island-echoes/a',{method:'POST'}),req('/file-island-echoes/a',{headers:{range:'bytes=0-1'}})])assert(!w.eligible(r));});
test('install is atomic and never forces an update',async()=>{const h=harness();h.fail();await assert.rejects(h.worker.install());assert(!h.stores.has(h.worker.shell));assert.deepEqual(h.calls,[]);});
test('navigation uses matching cached shell offline and online',async()=>{const h=harness();await h.worker.install();const r={url:'https://example.test/file-island-echoes/deep?x',method:'GET',mode:'navigate',headers:new Headers()};assert.match(await(await h.worker.fetchRequest(r)).text(),/shell:/);h.setOffline();assert.match(await(await h.worker.fetchRequest(r)).text(),/shell:/);assert.equal(h.calls.length,0);});
test('visited assets survive offline; missing assets fail softly',async()=>{const h=harness(),r=req('/file-island-echoes/assets/pic.webp');await h.worker.fetchRequest(r);h.setOffline();assert.equal(await(await h.worker.fetchRequest(r)).text(),'network');assert.equal((await h.worker.fetchRequest(req('/file-island-echoes/assets/unseen.webp'))).status,503);});
test('404 is not cached and unrelated caches survive activation',async()=>{const h=harness();await h.env.caches.open('another-app');await h.env.caches.open('file-island-echoes-shell-old');await h.worker.fetchRequest(req('/file-island-echoes/assets/missing.webp'));assert.equal((await h.env.caches.open(h.worker.runtime)).map.size,0);await h.worker.activate();assert(h.stores.has('another-app'));assert(!h.stores.has('file-island-echoes-shell-old'));assert(h.stores.has(h.worker.runtime));});
test('runtime cache is bounded',async()=>{const h=harness();for(let i=0;i<183;i++)await h.worker.fetchRequest(req('/file-island-echoes/assets/'+i+'.webp'));assert.equal((await h.env.caches.open(h.worker.runtime)).map.size,180);});

test('revised runtime content does not reuse stale bytes while identical revisions do',async()=>{const h=harness(),r=req('/file-island-echoes/assets/pic.webp');const config={base:'/file-island-echoes/',build:'one',files:[],revisions:{'/file-island-echoes/assets/pic.webp':'a'}};await createWorker(h.env,config).fetchRequest(r);const count=h.calls.length;await createWorker(h.env,{...config,build:'two'}).fetchRequest(r);assert.equal(h.calls.length,count);await createWorker(h.env,{...config,revisions:{'/file-island-echoes/assets/pic.webp':'b'}}).fetchRequest(r);assert.equal(h.calls.length,count+1);});
