import type {CharacterDefinition,CharacterId,EvolutionDefinition,FormDefinition} from '../types';
const deck=(attack:string,guard:string,utility:string)=>[attack,attack,attack,guard,guard,'guard','guard','cheer','food',utility];
export const CHARACTERS:Record<CharacterId,CharacterDefinition>={
 tai:{id:'tai',name:'신태일',partner:'아구몬',crest:'용기',icon:'attack',color:'#e8ad62',style:'먼저 나서되, 물러날 때도 아는 돌파형',difficulty:'쉬움',keywords:['돌진','화상','위험 보상'],forms:['agumon','greymon','metal'],startDeck:deck('flame','resolve','ember'),exclusive:['flame','courage','rush','ember','resolve','pressure'],passive:'에너지 3 이상에서 쓰는 턴의 첫 공격에 피해 +2. 진화 단계마다 +1 추가.',ability:{name:'용기의 결단',condition:'이번 전투에서 공격 카드 2장 사용',text:'부담 +3. 이번 턴 공격 피해 +4, 진화 에너지 +1. 전투당 1회.'},intro:'태일은 가장 먼저 신호를 향해 달리다가 멈춘다. 아구몬이 숨을 고를 때까지, 이번에는 곁에서 기다리기로 한다.',retry:'“앞장서는 건 혼자 달리는 것과 다르구나. 다시 같이 가자, 아구몬.”',preboss:'“내가 앞에 설게. 하지만 네가 힘들면 말해 줘.” 아구몬이 태일의 손을 잡는다. “그럼 나도 있는 힘껏 대답할게!”',ending:'태일은 되찾은 길의 맨 앞에서 뒤를 돌아본다. 모두의 발걸음을 확인하고서야 다시 걷는다. 아구몬은 그 옆에서 다음 도시락 이야기를 꺼낸다.'},
 matt:{id:'matt',name:'매튜',partner:'파피몬',crest:'우정',icon:'bond',color:'#89bddd',style:'다른 카드 종류를 이어 쓰며 빈틈을 메우는 연계형',difficulty:'어려움',keywords:['연계','보존','반격'],forms:['gabumon','garurumon','were-garurumon'],startDeck:deck('blue','matt','feint'),exclusive:['blue','matt','feint','counter','link','howl'],passive:'다른 종류의 카드를 연속 사용하면 연계 +1, 방어 +2. 완전체에서 추가 방어 +1. 같은 종류면 연계 초기화, 최대 4.',ability:{name:'맡길 수 있는 마음',condition:'연계 2 이상, 손패 1장 이상',text:'고른 손패 1장을 지금 보관해 다음 턴에 받습니다. 방어 +6, 에너지 +1. 전투당 1회.'},intro:'매튜는 혼자 다리를 건너려다 파피몬의 발소리에 돌아선다. 뒤에서 기다려 주는 친구도 길을 함께 찾을 수 있다는 것을 떠올린다.',retry:'“이번엔 혼자 버티지 않을게. 파피몬, 다음 수를 같이 생각하자.”',preboss:'흔들리는 길목에서 매튜가 파피몬에게 먼저 길을 맡긴다. “네가 지켜 준 만큼, 이번에는 내가 이어 갈게.”',ending:'매튜는 하모니카를 꺼내 잠깐 불다가 친구에게 자리를 내어 준다. 파피몬은 말없이 곁에 앉는다. 혼자 끝내야 할 모험은 아니었다.'},
 sora:{id:'sora',name:'한소라',partner:'피요몬',crest:'사랑',icon:'guard',color:'#e6a598',style:'보호한 힘을 공격으로 바꾸는 안정형',difficulty:'쉬움',keywords:['보호','재생','부담 관리'],forms:['biyomon','birdramon','garudamon'],startDeck:deck('feather','sora','regen'),exclusive:['feather','sora','regen','wind','embrace','flare-wing'],passive:'턴의 첫 방어 카드에 방어 +2, 부담 -1. 진화 단계마다 추가 방어 +1.',ability:{name:'함께 쉬어 갈 용기',condition:'방어도 8 이상 또는 체력 70% 이하',text:'체력 10 회복, 방어 +12, 부담 -3. 전투당 1회.'},intro:'소라는 친구들의 상태부터 살핀다. 피요몬이 조용히 묻는다. “소라는 괜찮아?” 그 질문에, 소라는 처음으로 자신의 지친 손을 바라본다.',retry:'“피요몬, 나도 조금 무서웠어. 함께 쉬고 다시 날아 보자.”',preboss:'소라는 피요몬의 날개를 펴 주다가 자신의 떨림을 숨기지 않는다. 피요몬이 그 손 위에 날개를 포갠다. 돌봄은 한쪽만의 몫이 아니다.',ending:'소라는 괜찮다는 말 대신 오늘 힘들었던 일을 이야기한다. 피요몬은 끝까지 듣고 함께 웃는다. 누구도 홀로 씩씩할 필요가 없는 밤이다.'},
 koushiro:{id:'koushiro',name:'장한솔',partner:'텐타몬',crest:'지식',icon:'draw',color:'#a7b8ea',style:'행동 순서와 덱의 다음 수를 읽는 예측형',difficulty:'어려움',keywords:['분석','노출','감전'],forms:['tentomon','kabuterimon','mega-kabuterimon'],startDeck:deck('shock','scan','analysis'),exclusive:['shock','analysis','scan','chain','expose','probe'],passive:'이번 탐험에서 처음 만난 적에게 노출 1. 적의 다음 두 행동을 상세 분석 화면에서 확인할 수 있습니다.',ability:{name:'아직 풀리지 않은 답',condition:'2턴 이후, 지원 카드 1장 사용, 뽑기 더미 1장 이상',text:'뽑기 더미 상단 최대 3장을 원하는 순서로 배치. 모든 적 노출 +2, 에너지 +1. 전투당 1회.'},intro:'한솔은 반복되는 신호를 표로 정리한다. 같은 수치 옆에서 텐타몬의 목소리만 조금씩 달랐다. 그 차이는 오류로 지워도 되는 것일까.',retry:'“틀린 가설도 기록할게요. 텐타몬의 생각도 함께요.”',preboss:'한솔은 완벽한 계산이 끝나기 전에 텐타몬을 바라본다. “이번에는 네 감각을 믿겠습니다.” 데이터에 없던 대답이 길을 연다.',ending:'한솔의 기록 마지막 줄에는 결론 대신 질문이 남는다. 텐타몬은 그것이 마음에 든다고 말한다. 알아 간다는 것은 듣기를 멈추지 않는 일이었다.'},
 mimi:{id:'mimi',name:'이미나',partner:'팔몬',crest:'순수',icon:'heal',color:'#b6ce84',style:'정화와 개화를 쌓아 꽃피우는 운영형',difficulty:'보통',keywords:['정화','개화','속박'],forms:['palmon','togemon','lillymon'],startDeck:deck('ivy','bloom','mimi'),exclusive:['ivy','mimi','bloom','bind','seed','garden'],passive:'한 행동으로 자신의 해로운 효과를 실제 제거하면 개화 +1. 카드로도 얻을 수 있으며 최대 6. 진화 후 개화 연계 공격 강화.',ability:{name:'있는 그대로의 마음',condition:'개화 2 이상 또는 해로운 효과가 있음',text:'자신의 오염·화상·약화 모두 정화. 개화당 체력 2 회복과 모든 적 피해 3, 최대 6중첩. 개화 소비. 전투당 1회.'},intro:'미나는 낯선 울음소리에 발을 멈춘다. 무서우면서도 그냥 지나치고 싶지 않다. 팔몬은 둘 다 솔직한 마음이라며 잎을 내민다.',retry:'“속상한 건 속상한 거야. 그래도 팔몬, 다시 도와주고 싶어.”',preboss:'미나는 적에게 화가 난다고, 동시에 슬프다고 말한다. 팔몬이 고개를 끄덕인다. 하나의 마음만 골라야 하는 것은 아니다.',ending:'미나는 돌아오는 길의 작은 꽃들을 이름 없이 남겨 둔다. 팔몬이 함께 돌보면 된다고 말한다. 솔직한 마음이 머물 자리가 하나 늘었다.'},
 joe:{id:'joe',name:'정석',partner:'쉬라몬',crest:'성실',icon:'support',color:'#8fc9cd',style:'남겨 둔 자원과 방어를 다음 수로 바꾸는 비축형',difficulty:'쉬움',keywords:['비축','보급','방어'],forms:['gomamon','ikkakumon','zudomon'],startDeck:deck('fish','stock','joe'),exclusive:['fish','joe','stock','shell','harpoon','ration'],passive:'턴 종료에 남은 에너지를 최대 2만큼 비축합니다. 비축 최대 3. 해머 스파크와 문장이 비축을 활용합니다.',ability:{name:'끝까지 책임질게',condition:'비축 2 이상',text:'비축 모두 소비. 체력 50% 이하이면 회복 16, 아니면 예고 공격이 방어보다 크면 방어 16, 아니면 에너지 1 이하이면 에너지 +2, 그 외 카드 3장. 전투당 1회.'},intro:'정석은 준비물을 몇 번이나 확인한다. 쉬라몬은 그 손이 떨리는 것을 알아도 재촉하지 않는다. 두렵지 않아야 책임질 수 있는 것은 아니다.',retry:'“무서웠지만 도망친 건 아니야. 다음엔 더 잘 준비할게.”',preboss:'정석은 마지막 식량을 세고 가방을 닫는다. “완벽한 준비는 아니지만, 내가 맡은 일은 해낼게.” 쉬라몬이 먼저 힘차게 답한다.',ending:'정석은 빼곡한 점검표에 마지막 표시를 한다. 완벽했던 하루는 아니지만 모두 돌아왔다. 쉬라몬은 그 사실을 제일 크게 축하한다.'},
 tk:{id:'tk',name:'리키',partner:'파닥몬',crest:'희망',icon:'evolution',color:'#e9d898',style:'고비를 견디며 한 번의 기회를 만드는 역전형',difficulty:'어려움',keywords:['희망','역전','정화'],forms:['patamon','angemon','magna-angemon'],startDeck:deck('bubble','hope','prayer'),exclusive:['bubble','hope','prayer','dawn','resolve-hope','gate'],passive:'턴 시작에 체력 40% 이하이거나 손에 공격 카드가 없으면 희망 +1. 턴당 1, 최대 3. 피해를 받을 때마다 쌓이지 않습니다.',ability:{name:'아직 끝나지 않았어',condition:'희망 2 이상',text:'희망을 모두 소비해 한 번의 생존 또는 즉시 회복·보호를 선택합니다. 전투당 1회.',modes:[{id:'survive',name:'끝까지 버틸게',text:'다음 치명 피해 1회를 체력 1로 버티고 방어 12 획득.'},{id:'support',name:'지금 다시 일어설게',text:'체력 6 + 희망×3 회복, 방어 희망×4.'}]},intro:'리키는 끊긴 목소리가 돌아오지 않을까 봐 두렵다. 파닥몬이 귀를 움직이며 그의 이름을 부른다. 지금 들리는 대답부터 믿어 보기로 한다.',retry:'“무섭지만, 파닥몬 목소리가 들려. 우리 다시 해 보자.”',preboss:'리키는 사라진 신호를 기다리며 파닥몬을 안는다. “돌아올 수 있는 길을 남겨 두자.” 작은 날개가 어둠 쪽으로 펼쳐진다.',ending:'리키는 통신기를 끄지 않고 친구의 목소리를 기다린다. 파닥몬은 그의 무릎에서 졸기 시작한다. 기다림은 이제 혼자 견디는 시간이 아니다.'},
 kari:{id:'kari',name:'신나리',partner:'가트몬',crest:'빛',icon:'signal',color:'#d9c1e8',style:'적의 힘을 걷어 내고 남은 빛을 돌려주는 제어형',difficulty:'보통',keywords:['빛','표식','정화'],forms:['gatomon','gatomon-resonance','angewomon'],startDeck:deck('cat','light-mark','purge'),exclusive:['cat','light-mark','purge','moon','radiance','mercy'],passive:'적의 방어·강화 또는 자신의 해로운 효과를 실제 제거한 행동마다 빛 +1, 최대 6. 빛의 공명 뒤 표식 공격이 강화됩니다.',ability:{name:'남겨진 빛을 향해',condition:'빛 2 이상 또는 자신의 오염 2 이상',text:'적 전체 방어·강화와 자신의 오염·화상·약화를 정화하고 빛을 소비해 공격 또는 보호. 전투당 1회.',modes:[{id:'attack',name:'빛으로 길을 열기',text:'모든 적에게 피해 12 + 빛×2.'},{id:'guard',name:'남은 빛을 지키기',text:'방어 10 + 빛×3, 체력 5 회복.'}]},intro:'나리는 검은 데이터 사이에서 작은 빛을 본다. 가트몬은 가까이 가기 전에 손을 잡는다. 도와주고 싶다는 마음에도 서로를 지킬 거리가 필요하다.',retry:'“모두를 한 번에 구할 수는 없었어. 가트몬, 다음엔 우리도 지키자.”',preboss:'나리는 적에게 남은 목소리에 귀를 기울인다. 가트몬은 그녀 앞을 지킨다. 공감한다는 것은 공격을 그대로 받아 주는 일이 아니다.',ending:'나리는 사라진 어둠보다 남아 있는 작은 목소리를 기억한다. 가트몬은 그 옆에서 조용히 눈을 감는다. 두려움에도 빛이 머물 자리가 생겼다.'},
};
export const FORMS:Record<string,FormDefinition>={};
export const EVOLUTIONS:EvolutionDefinition[]=[];
const lines:[CharacterId,string[],string[],string[],number[],number][]=[
 ['tai',['agumon','greymon','metal'],['아구몬','그레이몬','메탈그레이몬'],['flame','nova','missile'],[64,80,100],7],
 ['matt',['gabumon','garurumon','were-garurumon'],['파피몬','가루몬','워가루몬'],['blue','blue-plus','wolf-claw'],[64,80,98],6],
 ['sora',['biyomon','birdramon','garudamon'],['피요몬','버드라몬','가루다몬'],['feather','meteor-wing','shadow-wing'],[66,82,100],7],
 ['koushiro',['tentomon','kabuterimon','mega-kabuterimon'],['텐타몬','캅테리몬','아트라캅테리몬'],['shock','mega-blaster','horn-buster'],[62,80,98],6],
 ['mimi',['palmon','togemon','lillymon'],['팔몬','니드몬','릴리몬'],['ivy','needle','flower-cannon'],[64,80,98],7],
 ['joe',['gomamon','ikkakumon','zudomon'],['쉬라몬','원뿔몬','쥬드몬'],['fish','harpoon-plus','hammer'],[68,84,102],6],
 ['tk',['patamon','angemon','magna-angemon'],['파닥몬','엔젤몬','홀리엔젤몬'],['bubble','heavens-knuckle','holy-gate'],[64,80,98],6],
 ['kari',['gatomon','gatomon-resonance','angewomon'],['가트몬','가트몬 · 빛의 공명','엔젤우몬'],['cat','cat-resonant','holy-arrow'],[64,80,98],7],
];
for(const [owner,ids,names,cards,hp,bond] of lines){
 ids.forEach((id,i)=>{const stage=i as 0|1|2;FORMS[id]={name:names[i],tag:owner==='kari'?(i===2?'완전체':i===1?'성숙기 · 공명 강화':'성숙기'):['성장기','성숙기','완전체'][i],hp:hp[i],bonus:i===2?2:0,stage,owner,art:id==='gatomon-resonance'?'gatomon':id,basic:cards[0],upgraded:cards[i],accent:CHARACTERS[owner].color,description:i===0?CHARACTERS[owner].style:`${i===1?'기본 공격 카드 강화':'강화 공격 2장 전용 기술로 교체'}. 최대 체력 +${hp[i]-hp[i-1]}, 같은 수치 회복.${i===2?' 모든 공격 +2.':''}${owner==='kari'&&i===1?' 새로운 진화체가 아닌 게임용 능력 강화입니다.':''}`};});
 EVOLUTIONS.push({from:ids[0],to:ids[1],energy:5,bond:0,burden:0,condition:'진화 에너지 5',resonance:owner==='kari'}, {from:ids[1],to:ids[2],energy:owner==='tai'?14:12,bond,burden:0,condition:`진화 에너지 ${owner==='tai'?14:12} · 유대 ${bond} 이상`});
}
FORMS.skull={name:'스컬그레이몬',tag:'완전체 · 강제 진화',description:'메가 플레임 2장 → 그라운드 제로. 모든 공격 +4. 턴 종료 체력 2 소모. 최대 체력 +10, 같은 수치 회복.',hp:90,bonus:4,stage:2,owner:'tai',art:'skull',basic:'flame',upgraded:'zero',accent:'#ca9fdd'};
EVOLUTIONS.push({from:'greymon',to:'skull',energy:12,bond:0,burden:6,condition:'진화 에너지 12 · 부담 6 이상'});

FORMS.metal.description+=" 방어 카드 방어도 +2.";
