export {CARDS,KEYWORDS,describeCard} from './content/cards';
export {CHARACTERS,FORMS,EVOLUTIONS} from './content/characters';
export {ENEMIES,NPCS} from './content/enemies';
export {STORIES,storyId} from './content/stories';
export {CHAPTERS,chapterOf,zoneAt,sceneAt} from './content/chapters';
import {CHAPTERS} from './content/chapters';
import {CHARACTERS} from './content/characters';
export const MAP=CHAPTERS.file.map;
export const ZONES=CHAPTERS.file.zones;
export const START_DECK=CHARACTERS.tai.startDeck;
export const REWARD_POOL=['guard','cheer','food','light','claw'];
export const RECOVERY={supply:12,rest:20,train:6} as const;
export const BOSS_RAGE={turn:5,interval:4,damage:6} as const;
