import './style.css';
import { CARDS, ENEMIES, FORMS, MAP, STORIES, ZONES, zoneAt } from './data';
import { cardStats, chooseEvent, endTurn, enterNode, evolve, evolutionOptions, intent, newRun, nodeOf, playCard, rest, reward, useSupply } from './engine';
import { loadSave, updateArchive, writeSave } from './storage';
import { island, sprite } from './art';
import { sound } from './audio';
import type { CardId, Form, Run } from './types';

const loaded=loadSave();const save=loaded.save;
let warning=loaded.warning,view:'title'|'game'='title',modal='',pendingForm:Form|null=null,notice='',attack=false;
const root=document.querySelector<HTMLDivElement>('#app')!;
const esc=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const btn=(label:string,action:string,cls='',attrs='')=>`<button class="${cls}" data-action="${action}" ${attrs}>${label}</button>`;
const icon=(type:string)=>({battle:'⚔',elite:'◆',event:'◇',rest:'♨',boss:'✦',attack:'↗',guard:'⬡',support:'✧',defend:'⬡',corrupt:'◈',drain:'↗'} as Record<string,string>)[type]||'✦';
const kindName=(type:string)=>({battle:'전투',elite:'강적',event:'이야기',rest:'휴식',boss:'최종 보스',attack:'공격',guard:'방어',support:'지원'} as Record<string,string>)[type]||type;
function persist(previous:Run|null) {updateArchive(save,previous);if(!writeSave(save))warning='이 브라우저에서 저장할 수 없습니다. 새로고침하면 진행 상황이 사라질 수 있습니다.';}
function act(fn:(r:Run)=>void) {if(!save.run)return;const before=structuredClone(save.run);fn(save.run);persist(before);render();}
function meter(value:number,max:number,cls='') {return `<div class="meter ${cls}"><i style="width:${Math.max(0,Math.min(100,value/max*100))}%"></i></div>`;}
function header(){return `<header class="topbar"><button data-action="home" class="brand" aria-label="타이틀로"><span class="brand-symbol">◈</span><span>디지몬 어드벤처<small>파일섬의 잔향</small></span></button><div class="top-actions"><span class="connection"><i></i> FILE ISLAND · 접속 중</span>${btn('도감','archive','quiet')}${btn(save.settings.muted?'소리 꺼짐':'소리 켜짐','sound','quiet')}${btn('정보','credits','quiet')}${btn('설정','settings','quiet')}</div></header>`;}
function title(){const r=save.run;return `<main class="title-screen"><div class="title-copy"><div class="eyebrow"><span></span> 비공식 팬메이드 모험 · EPISODE 01</div><p class="series-title">디지몬 어드벤처</p><h1>파일섬의<br/><em>잔향</em><span class="title-cross">✦</span></h1><p class="intro">낯익은 숲. 되풀이되는 신호.<br/>다시, 너와 함께 모험을 시작할 시간.</p><div class="start-actions">${btn('새 탐험 시작 <span>→</span>','new','primary large')}${r&&r.screen!=='result'?btn(`이어서 탐험 <small>${ZONES[zoneAt(r.row)]} · ${r.row+1}/11</small>`,'continue','secondary large'):''}</div><p class="playtime">약 10–15분 <span>·</span> 로그인 없이 플레이 <span>·</span> 자동 저장</p></div><div class="title-world"><div class="world-label"><span class="tiny-square"></span> DIGITAL WORLD <small>FILE ISLAND / 1999</small></div>${island()}<div class="partner-intro"><div class="mini-sprite">${sprite('agumon')}</div><div><small>YOUR PARTNER</small><strong>아구몬</strong><p>“태일아, 이번에도 같이 가는 거지?”</p></div><span class="signal">▂▄▆</span></div><div class="world-coordinate">35° 42′ N &nbsp; / &nbsp; 신호 복원 중 <span>01 — FILE ISLAND</span></div></div><footer class="title-footer"><span>모험 · 우정 · 그리고 진화</span><p>1999년 「디지몬 어드벤처」 기반 비공식 팬게임입니다.<br/>반복 현상, 사건과 진화 조건은 팬게임의 창작 설정입니다. 원작 권리는 각 권리자에게 있습니다.</p><span>FAN PROJECT<br/>v0.1</span></footer></main>`;}
function status(r:Run){return `<section class="statusbar" aria-label="파트너 상태"><div class="status-partner">${sprite(r.form)}<div><small>신태일의 파트너 · ${FORMS[r.form].tag}</small><strong>${FORMS[r.form].name}</strong></div></div><div class="health"><span>체력 <b>${r.hp} <small>/ ${r.maxHp}</small></b></span>${meter(r.hp,r.maxHp)}</div><div class="stat"><small>진화 에너지</small><b class="cyan">✧ ${r.evoEnergy}</b></div><div class="stat"><small>유대</small><b>♡ ${r.bond}</b></div><div class="stat"><small>부담</small><b class="${r.burden>=6?'orange':''}">◈ ${r.burden}</b></div><div class="stat"><small>오염</small><b>${r.corruption}</b></div>${btn(`보급품 ${r.supplies}<small>체력 +18</small>`,'supply','supply',`${r.supplies===0||r.hp===r.maxHp||!['map','battle','event','rest'].includes(r.screen)?'disabled':''}`)}${btn(`덱 ${r.deck.length}장`,'deck','quiet')}</section>`;}
function map(r:Run){return `<main class="game-content"><div class="section-heading"><div><div class="eyebrow">EXPLORATION / ${String(r.row+1).padStart(2,'0')}</div><h1>친구들의 신호를 따라서</h1><p>연결된 길 중 하나를 선택하세요. ${r.row===0?'첫 전투에서 조작을 익힐 수 있습니다.':'다음 목적지는 '+ZONES[zoneAt(r.row)]+'입니다.'}</p></div><span class="chapter-count">${r.path.length}<small> / 11 탐험</small></span></div><div class="map-layout"><div class="route-map">${ZONES.map((z,zi)=>`<section class="zone ${zoneAt(r.row)===zi?'active-zone':''}"><div class="zone-heading"><span>0${zi+1}</span><h2>${z}</h2><small>${zi===0?'FOREST':zi===1?'FACTORY':'INFINITY MOUNTAIN'}</small></div><div class="node-rows">${MAP.map((nodes,row)=>zoneAt(row)!==zi?'':`<div class="node-row ${row===r.row?'current-row':''}"><span class="step-dot">${row+1}</span>${nodes.map(n=>{const visited=r.path.includes(n.id);return `<button class="map-node ${n.type} ${visited?'visited':''} ${row===r.row?'available':''}" data-action="node:${n.id}" ${row!==r.row?'disabled':''}><span class="node-icon">${visited?'✓':icon(n.type)}</span><span><small>${kindName(n.type)} ${row===r.row?'· 선택 가능':''}</small><strong>${n.name}</strong><span class="node-note">${n.note}</span></span>${row===r.row?'<b class="node-arrow">↗</b>':''}</button>`;}).join('')}</div>`).join('')}</div></section>`).join('')}</div><aside class="partner-panel"><div class="eyebrow">PARTNER LINK</div><div class="partner-stage">${sprite(r.form)}<span class="stage-ring"></span></div><h2>${FORMS[r.form].name}</h2><p class="partner-quote">${r.burden>=6?'“조금 힘들어… 내 목소리가 들려?”':r.hp<r.maxHp*.4?'“잠깐 쉬었다 가면 안 될까?”':'“우리가 함께라면 해낼 수 있어!”'}</p><div class="evolution-list">${evolutionOptions(r).map(e=>btn(`<small>${e.form==='skull'?'⚠ 강제 진화':'진화 가능성'}</small><strong>${FORMS[e.form].name} <span>→</span></strong><span>${e.condition}</span>`,`preview:${e.form}`,`evolve-option ${e.form==='skull'?'risky':''}`,!e.ready?'disabled':'')).join('')||'<div class="complete-form">✦ 완전체의 힘이 덱에 반영되었습니다.</div>'}</div><p class="checkpoint">✓ 행동 후 자동 저장<br/>타이틀로 돌아가도 이어할 수 있어요.</p>${btn('탐험 안내','help','quiet wide')}</aside></div></main>`;}
function card(id:CardId,action:string,r:Run,disabled=false){const c=cardStats(r,id);const text=c.text+(r.form==='metal'&&c.damage?' 진화 보너스 +3.':r.form==='skull'&&c.damage?' 진화 보너스 +5.':'')+(r.form==='metal'&&c.kind==='guard'?' 방어 보너스 +3.':'');return `<button class="game-card ${c.kind}" data-action="${action}" ${disabled?'disabled':''} aria-label="${c.name}, 에너지 ${c.cost}. ${text}"><div class="card-top"><span class="cost">${c.cost}</span><small>${kindName(c.kind)}</small></div><div class="card-art">${icon(c.kind)}<span>${c.damage?c.damage:c.block?c.block:'✦'}</span></div><strong>${c.name}</strong><p>${text}</p><div class="card-bottom">${c.kind==='attack'?'PARTNER SKILL':'BOND SKILL'} <span>◆</span></div></button>`;}
function battle(r:Run){const b=r.battle!;return `<main class="battle-content"><div class="battle-heading"><div><div class="eyebrow">${ZONES[zoneAt(r.row)]} / ${kindName(nodeOf(r)!.type)}</div><h1>${nodeOf(r)!.name}</h1></div><div class="turn-info">TURN <b>${String(b.turn).padStart(2,'0')}</b>${btn('전투 안내','help','quiet')}</div></div>${save.settings.guide&&b.turn===1?'<div class="guide-banner">① 적을 눌러 대상을 선택 → ② 카드를 눌러 사용 → ③ 턴 종료. 적 머리 위의 예고를 먼저 확인하세요.</div>':''}<div class="battlefield ${nodeOf(r)?.type==='boss'?'boss-field':''} ${attack?'attack-flash':''}"><div class="terrain"></div><div class="fighter player"><div class="fighter-label">${FORMS[r.form].name} <span>⬡ 방어 ${b.block}</span></div>${sprite(r.form,'player-sprite')}<div class="fighter-base"></div><div class="status-tags">${r.corruption?`<span>◈ 오염 ${r.corruption} · 턴 종료 체력 소모</span>`:''}${r.form==='skull'?'<span>반동 · 턴 종료 체력 -2</span>':''}</div></div><span class="versus">VS</span><div class="enemy-group">${b.enemies.map((e,i)=>{const a=intent(r,i);return `<button class="fighter enemy ${b.target===i?'targeted':''} ${e.hp<=0?'defeated':''}" data-action="target:${i}" ${e.hp<=0?'disabled':''} aria-label="${ENEMIES[e.id].name} 대상으로 선택"><div class="intent ${a.type}">${e.hp<=0?'정화 완료':`${icon(a.type)} ${a.label} <b>${a.value}</b>`}</div>${sprite(e.id)}<div class="fighter-base"></div><strong>${ENEMIES[e.id].name}</strong><div class="enemy-health"><span>${e.hp} / ${e.maxHp}</span>${meter(e.hp,e.maxHp,'enemy-meter')}</div><div class="enemy-badges">${e.block?`⬡ ${e.block} `:''}${e.weak?`약화 ${e.weak}턴`:''}</div><span class="target-label">${e.hp<=0?'전투 불능':b.target===i?'⌖ 선택한 대상':'대상 선택'}</span></button>`;}).join('')}</div></div><div class="hand-toolbar"><div class="energy-orb">${b.energy}<small>에너지</small></div><div><strong>너의 선택이 우리의 힘이 돼.</strong><p>공격은 선택한 적에게 적용됩니다. 손패 ${b.hand.length}장</p></div><div class="pile-counts">뽑기 <b>${b.draw.length}</b><span> / </span>버림 <b>${b.discard.length}</b></div>${btn('턴 종료 →','end','primary end-turn')}</div><div class="hand" aria-label="손패">${b.hand.map((id,i)=>card(id,`card:${i}`,r,CARDS[id].cost>b.energy)).join('')||'<p class="empty-hand">손패를 모두 사용했습니다. 턴을 종료하세요.</p>'}</div><details class="battle-log"><summary>전투 기록 · ${b.log[0]||''}</summary><ol>${b.log.map(l=>`<li>${esc(l)}</li>`).join('')}</ol></details></main>`;}
function eventScreen(r:Run){const s=STORIES[nodeOf(r)!.event!];return `<main class="story-screen"><div class="story-art">${island()}<div class="story-art-sprite">${sprite(r.form)}</div><span class="eyebrow">FRIENDSHIP SIGNAL / ${ZONES[zoneAt(r.row)]}</span></div><div class="story-copy"><div class="eyebrow">◇ 이야기 이벤트</div><h1>${s.title}</h1><p class="speaker">${s.speaker}</p><blockquote>${s.quote}</blockquote><p>${s.body}</p><div class="choices">${s.choices.map((c,i)=>btn(`<strong>${c.label}<span>→</span></strong><small>${c.text}</small>`,`choice:${i}`,'choice')).join('')}</div></div></main>`;}
function restScreen(r:Run){return `<main class="center-screen"><div class="eyebrow">CAMP / 잠시 쉬어 가는 모험</div><div class="camp-art">${sprite(r.form)}<span class="camp-fire">♨</span></div><h1>${nodeOf(r)!.name}</h1><p class="speaker">한소라 · 피요몬</p><blockquote>“무리하지 마. 아구몬이 웃어야 태일이도 힘이 나잖아.”</blockquote><div class="choices rest-choices">${btn('<strong>파트너와 푹 쉰다 →</strong><small>체력 +26 · 부담 -4 · 오염 -2 · 유대 +2</small>','rest:rest','choice')}${btn('<strong>짧게 쉬고 함께 훈련한다 →</strong><small>체력 +10 · 진화 에너지 +5 · 부담 +2</small>','rest:train','choice')}</div></main>`;}
function rewardScreen(r:Run){return `<main class="center-screen reward-screen"><div class="eyebrow">BATTLE CLEAR / 오염된 톱니바퀴 정화</div><h1>함께 싸운 기억이 힘으로</h1><p>덱에 추가할 카드 1장을 선택하세요. 넘어가도 괜찮습니다.</p><div class="reward-summary">✧ 진화 에너지 +${nodeOf(r)?.type==='elite'?7:5} <span>♡ 유대 +1</span> 완료 시 체력 +5</div><div class="reward-cards">${r.rewards.map(id=>card(id,`reward:${id}`,r)).join('')}</div>${btn('카드를 받지 않고 계속 →','skip','secondary')}</main>`;}
function evolutionScreen(r:Run){return `<main class="center-screen evolution-screen"><div class="evolution-rays"></div><div class="eyebrow">DIGIVOLUTION / ${r.form==='skull'?'FORCED LINK':'PARTNER LINK ESTABLISHED'}</div><p>${FORMS[r.evolvedFrom||'agumon'].name}, 진화!</p><div class="evolution-sprite">${sprite(r.form)}</div><h1>${FORMS[r.form].name}</h1><span class="form-tag">${FORMS[r.form].tag}</span><p class="evolution-effect">${FORMS[r.form].description}</p>${btn('함께 앞으로 →','evolution-done','primary large')}</main>`;}
function resultScreen(r:Run){return `<main class="center-screen result-screen"><div class="eyebrow">EXPEDITION ${r.won?'COMPLETE':'ENDED'}</div><span class="result-seal">${r.won?'✦':'◇'}</span><h1>${r.won?'다시 이어진 파일섬':'모험은 아직 끝나지 않았어'}</h1><blockquote>${r.won?'“태일아, 친구들 신호가 들려!”':'“미안해, 아구몬. 다음에는 함께 속도를 맞추자.”'}</blockquote><p>${r.won?'데블몬이 쓰러지고 무한산의 데이터가 안정을 되찾았습니다.<br/>흩어졌던 목소리들이 하나씩 돌아옵니다.':'파트너를 데리고 안전한 곳으로 돌아왔습니다.<br/>발견한 도감과 이야기는 다음 모험에도 남습니다.'}</p><div class="result-stats"><div><b>${r.path.length}</b><span>완료한 장소</span></div><div><b>${r.battles}</b><span>전투 승리</span></div><div><b>${FORMS[r.form].name}</b><span>도달 진화체</span></div></div><p class="checkpoint">✓ 도감과 탐험 기록 저장 완료 · 다음 탐험은 새로운 덱과 아구몬으로 시작합니다.</p><div class="result-actions">${btn('새 탐험 시작 →','new','primary')}${btn('도감 보기','archive','secondary')}${btn('타이틀로','home','quiet')}</div></main>`;}
function help(){return `<h2>함께 떠나는 첫 모험</h2><p>지도에서 매 단계 하나의 길을 고릅니다. 총 11곳, 전투는 보스 포함 5회입니다.</p><ol class="help-list"><li><b>카드 전투</b> — 매 턴 에너지 3, 카드 5장. 적을 고른 뒤 카드를 누르면 즉시 사용됩니다. 남은 손패는 턴 종료 때 버립니다.</li><li><b>예고를 읽기</b> — ↗ 공격 / ⬡ 방어 / ◈ 오염. 방어는 피해를 막고 다음 내 턴 시작에 사라집니다. 약화는 적의 공격을 40% 줄입니다.</li><li><b>오염과 보급</b> — 오염 수치만큼 턴 종료에 체력을 잃습니다. 새로 받은 오염은 다음 턴부터 적용됩니다. 정화 카드·휴식으로 제거하세요. 보급품은 에너지 없이 체력 18을 회복합니다.</li><li><b>진화</b> — 지도에서 조건과 효과를 확인하고 선택합니다. 높은 부담에서 강제 진화를 선택하면 강한 힘과 자기 손상을 함께 얻습니다. 자동 진화는 없습니다.</li><li><b>저장</b> — 카드 사용, 턴 종료, 노드 완료 등 행동 직후 자동 저장합니다. 새로고침 후 타이틀의 이어하기로 복귀하세요.</li></ol><p class="muted">8인 일행이 함께 존재하는 팬게임 시점입니다. 반복 사건과 진화 조건은 원작 공식 설정이 아닙니다.</p>${btn('알겠어, 출발!','close','primary wide')}`;}
function modalContent(){const r=save.run;if(modal==='help')return help();if(modal==='new')return `<h2>새 탐험을 시작할까요?</h2><p>진행 중인 탐험이 새 아구몬과 시작 덱으로 교체됩니다. 도감과 설정은 유지됩니다.</p>${btn('새 탐험 시작','confirm-new','primary wide')}${btn('현재 탐험 유지','close','quiet wide')}`;
 if(modal==='credits')return `<h2>게임 정보 · 크레딧</h2><p>개발자와 지인 1–2명이 함께 테스트하는 소규모 비영리 팬 프로토타입입니다.</p><p lang="en">Unofficial, non-commercial fan project.<br/>This project is not affiliated with or endorsed by Bandai, Toei Animation, or any related rights holder.<br/>Third-party names and characters belong to their respective rights holders.</p><p>반다이, 토에이 애니메이션 및 관련 권리자와 제휴하거나 승인을 받은 프로젝트가 아닙니다. 제3자의 이름과 캐릭터에 관한 권리는 각 권리자에게 있습니다.</p><h3>제작</h3><p>코드와 임시 픽셀 아트는 이 프로젝트를 위해 새로 작성했습니다. 효과음은 Web Audio로 합성하고, 한국어 글꼴은 기기의 기본 글꼴을 사용합니다. 영상 캡처, 게임 추출 스프라이트, 공식 로고·음원은 사용하지 않았습니다.</p><h3>이 모험에 대하여</h3><p>1999년 「디지몬 어드벤처」를 바탕으로 합니다. 반복 현상, 독립 사건과 진화 조건은 팬게임을 위한 창작 설정입니다.</p><h3>공유와 저장</h3><p>공개 URL은 누구나 열 수 있습니다. 검색 제외 요청은 접근 통제가 아닙니다. 광고, 후원, 결제, 분석 도구와 사용자 추적 기능은 없습니다. 게임 기록은 이 브라우저에만 저장됩니다.</p>`;
 if(modal==='settings')return `<h2>디지바이스 설정</h2><div class="setting-row"><div><b>효과음</b><p>카드 사용과 진화에 짧은 신호음</p></div>${btn(save.settings.muted?'꺼짐':'켜짐','sound','toggle',`aria-pressed="${!save.settings.muted}"`)}</div><div class="setting-row"><div><b>움직임 줄이기</b><p>부유 효과와 진화 애니메이션 끄기</p></div>${btn(save.settings.reducedMotion?'켜짐':'꺼짐','motion','toggle',`aria-pressed="${save.settings.reducedMotion}"`)}</div><div class="setting-row"><div><b>첫 턴 안내</b><p>다음 탐험에서도 표시할 수 있어요</p></div>${btn(save.settings.guide?'켜짐':'꺼짐','guide','toggle',`aria-pressed="${save.settings.guide}"`)}</div><p>저장은 이 브라우저에만 남습니다. 능력치를 올리는 영구 강화는 없습니다.</p>`;
 if(modal==='archive'){const a=save.archive;return `<div class="eyebrow">DIGITAL ARCHIVE</div><h2>우리의 모험 도감</h2><p>탐험 종료 ${a.runs}회 · 클리어 ${a.wins}회 · 최고 도달 ${a.best}/11</p><h3>파트너의 진화 · ${a.forms.length}/4</h3><div class="archive-grid">${Object.entries(FORMS).map(([id,f])=>`<div class="archive-item ${a.forms.includes(id as Form)?'':'locked'}">${sprite(id)}<strong>${a.forms.includes(id as Form)?f.name:'미발견'}</strong><small>${a.forms.includes(id as Form)?f.tag:'???'}</small></div>`).join('')}</div><h3>만난 디지몬 · ${a.enemies.length}/7</h3><div class="archive-enemies">${Object.entries(ENEMIES).map(([id,e])=>`<div class="archive-enemy ${a.enemies.includes(id)?'':'locked'}">${sprite(id)}<div><strong>${a.enemies.includes(id)?e.name:'미발견 디지몬'}</strong><p>${a.enemies.includes(id)?e.description:'탐험에서 만나면 기록됩니다.'}</p></div></div>`).join('')}</div><h3>발견한 이야기 · ${a.events.length}/9</h3><p>${a.events.map(id=>STORIES[id].title).join(' · ')||'친구들의 신호를 찾아보세요.'}</p><h3>도달한 구역</h3><p>${a.zones.map(i=>ZONES[i]).join(' → ')||'아직 탐험 기록이 없습니다.'}</p>`;}
 if(modal==='deck'&&r)return `<h2>파트너 덱 · ${r.deck.length}장</h2><p>진화로 바뀐 카드는 다음 전투부터 사용됩니다.</p><div class="deck-list">${[...new Set(r.deck)].map(id=>`<div><span class="cost">${CARDS[id].cost}</span><div><b>${CARDS[id].name} × ${r.deck.filter(c=>c===id).length}</b><p>${CARDS[id].text}</p></div></div>`).join('')}</div>`;
 if(modal==='evo'&&r&&pendingForm){const f=FORMS[pendingForm],o=evolutionOptions(r).find(e=>e.form===pendingForm)!;return `<div class="eyebrow">${pendingForm==='skull'?'⚠ 강제 진화 경고':'EVOLUTION PREVIEW'}</div><h2>${f.name}으로 진화</h2><div class="modal-sprite">${sprite(pendingForm)}</div><p>${f.description}</p>${pendingForm==='skull'?'<div class="danger-note"><b>이 진화는 이번 탐험 동안 되돌릴 수 없습니다.</b><p>매 턴 종료 체력 2 소모. 전용 공격은 추가로 체력 5를 소모합니다. 자기 손상으로 패배할 수 있으며 메탈그레이몬 경로를 선택할 수 없게 됩니다.</p></div>':''}<p>비용: 진화 에너지 ${o.cost} · 현재 ${r.evoEnergy}<br/>진화 후 에너지 ${r.evoEnergy-o.cost} · 최대 체력 ${f.hp}</p><p class="muted">팬게임용 진화 조건이며 공식 진화 규칙이 아닙니다.</p>${btn(pendingForm==='skull'?'위험을 이해하고 강제 진화':'파트너와 함께 진화','evolve',pendingForm==='skull'?'danger wide':'primary wide')}${btn('아직은 기다린다','close','quiet wide')}`;}return '';}
function render(){
 const r=save.run;
 const focusedAction=(document.activeElement as HTMLElement|null)?.dataset.action;
 const handScroll=root.querySelector('.hand')?.scrollLeft||0;
 document.body.classList.toggle('reduced-motion',save.settings.reducedMotion);
 root.innerHTML=header()+(warning?`<div class="save-warning" role="status">${warning}</div>`:'')+
  (view==='title'||!r?title():status(r)+({map:map,battle:battle,event:eventScreen,rest:restScreen,reward:rewardScreen,evolution:evolutionScreen,result:resultScreen}[r.screen])(r))+
  (notice?`<div class="toast" role="status">${esc(notice)}</div>`:'')+
  (modal?`<dialog aria-label="${modal==='evo'?'진화 미리보기':'게임 메뉴'}"><div class="dialog-top">${btn('✕','close','close-button','aria-label="닫기"')}</div>${modalContent()}</dialog>`:'');
 if(modal){
  const dialog=root.querySelector('dialog')!;
  dialog.showModal();
  dialog.addEventListener('cancel',e=>{e.preventDefault();modal='';render();});
 }
 const scope=modal?root.querySelector('dialog')!:root;
 const nextFocus=Array.from(scope.querySelectorAll<HTMLButtonElement>('button:not(:disabled)')).find(b=>b.dataset.action===focusedAction);
 if(nextFocus)nextFocus.focus({preventScroll:true});
 else if(focusedAction?.startsWith('card:'))root.querySelector<HTMLButtonElement>('[data-action="end"]')?.focus({preventScroll:true});
 const hand=root.querySelector('.hand');if(hand)hand.scrollLeft=handScroll;
}
function start(){save.run=newRun();view='game';modal=save.settings.guide?'help':'';persist(null);render();window.scrollTo(0,0);}
root.addEventListener('click',e=>{const el=(e.target as HTMLElement).closest<HTMLButtonElement>('[data-action]');if(!el||el.disabled)return;const [action,value]=el.dataset.action!.split(':');sound('click',save.settings.muted);
 if(action==='close'){modal='';render();return;}if(action==='home'){view='title';modal='';render();return;}if(action==='new'){if(save.run&&save.run.screen!=='result'){modal='new';render();}else start();return;}if(action==='confirm-new'){start();return;}if(action==='continue'){view='game';render();return;}
 if(['settings','archive','deck','help','credits'].includes(action)){modal=action;render();return;}
 if(['sound','motion','guide'].includes(action)){const k=action==='sound'?'muted':action==='motion'?'reducedMotion':'guide';save.settings[k]=!save.settings[k];persist(save.run);if(k==='muted')sound('click',save.settings.muted);render();return;}
 if(action==='preview'){pendingForm=value as Form;modal='evo';render();return;}
 if(action==='evolve'){modal='';act(r=>{if(pendingForm)evolve(r,pendingForm);});sound('evolve',save.settings.muted);window.scrollTo(0,0);return;}
 if(action==='evolution-done'){act(r=>{if(r.screen==='evolution')r.screen='map';});return;}
 if(action==='node'){act(r=>enterNode(r,value));window.scrollTo(0,0);return;}
 if(action==='target'){act(r=>{if(r.screen==='battle'&&r.battle&&(r.battle.enemies[+value]?.hp??0)>0)r.battle.target=+value;});return;}
 if(action==='card'){const was=save.run?.screen;attack=true;act(r=>{playCard(r,+value);});sound('attack',save.settings.muted);setTimeout(()=>{attack=false;root.querySelector('.attack-flash')?.classList.remove('attack-flash');},250);if(save.run?.screen!==was)window.scrollTo(0,0);return;}
 if(action==='end'){act(endTurn);return;}if(action==='supply'){const old=save.run?.supplies;act(useSupply);if(old!==save.run?.supplies){notice='보급품으로 체력 18을 회복했습니다.';render();setTimeout(()=>{notice='';root.querySelector('.toast')?.remove();},2200);}return;}
 if(action==='choice'){act(r=>chooseEvent(r,+value));window.scrollTo(0,0);return;}if(action==='rest'){act(r=>rest(r,value as 'rest'|'train'));window.scrollTo(0,0);return;}if(action==='reward'||action==='skip'){act(r=>reward(r,action==='skip'?undefined:value as CardId));window.scrollTo(0,0);}
});
render();
