import {test,expect,vi,afterEach} from 'vitest';
import {Pwa} from './pwa';
function setup(){const reload=vi.fn();vi.stubGlobal('window',{addEventListener:vi.fn(),setTimeout:vi.fn()});vi.stubGlobal('navigator',{onLine:true,userAgent:'Chromium',platform:'test',maxTouchPoints:0});vi.stubGlobal('location',{reload,origin:'http://localhost'});vi.stubGlobal('performance',{getEntriesByType:()=>[]});vi.stubGlobal('matchMedia',()=>({matches:false,addEventListener:vi.fn()}));vi.stubGlobal('fetch',vi.fn(async()=>new Response('ok')));const p=new Pwa(vi.fn()),postMessage=vi.fn();p.registration={waiting:{postMessage}} as unknown as ServiceWorkerRegistration;return {p,postMessage,reload};}
afterEach(()=>vi.unstubAllGlobals());
test('update waits for explicit apply, saves before message and reloads once',async()=>{const {p,postMessage,reload}=setup();p.controllerChanged();expect(reload).not.toHaveBeenCalled();const save=vi.fn(()=>{expect(postMessage).not.toHaveBeenCalled();return true;});await p.apply(true,save);expect(save).toHaveBeenCalledOnce();expect(postMessage).toHaveBeenCalledWith({type:'APPLY_UPDATE'});p.controllerChanged();p.controllerChanged();expect(reload).toHaveBeenCalledOnce();});
test('unsafe combat, offline and failed storage never activate',async()=>{for(const mode of ['combat','offline','storage']){const {p,postMessage}=setup();if(mode==='offline')vi.stubGlobal('navigator',{onLine:false});await p.apply(mode!=='combat',()=>mode!=='storage');expect(postMessage).not.toHaveBeenCalled();expect(p.applying).toBe(false);}});
test('unreachable server does not fake successful update',async()=>{const {p,postMessage}=setup();vi.stubGlobal('fetch',vi.fn(async()=>{throw Error();}));await p.apply(true,()=>true);expect(postMessage).not.toHaveBeenCalled();expect(p.message).toContain('연결하지 못했습니다');});
test('repeated apply does not activate twice',async()=>{const {p,postMessage}=setup();await p.apply(true,()=>true);await p.apply(true,()=>true);expect(postMessage).toHaveBeenCalledOnce();});
test('install button only appears with a capability; accepting prompt is not proof of installed',async()=>{const {p}=setup();expect(p.panel(true)).not.toContain('data-action="pwa-install"');p.prompt={prompt:vi.fn(async()=>{}),userChoice:Promise.resolve({outcome:'accepted'})} as any;expect(p.panel(true)).toContain('data-action="pwa-install"');await p.install();expect(p.installed).toBe(false);expect(p.prompt).toBeNull();});
test('iOS Safari instruction hides in standalone',()=>{const {p}=setup();vi.stubGlobal('navigator',{onLine:true,userAgent:'iPhone Safari',platform:'iPhone',maxTouchPoints:1});expect(p.panel(true)).toContain('공유 → 홈 화면에 추가');p.installed=true;expect(p.panel(true)).not.toContain('공유 → 홈 화면에 추가');});
test('concurrent apply only posts once while connectivity is pending',async()=>{const {p,postMessage}=setup();let resolve!:(r:Response)=>void;vi.stubGlobal('fetch',vi.fn(()=>new Promise<Response>(r=>resolve=r)));const first=p.apply(true,()=>true);await p.apply(true,()=>true);resolve(new Response('ok'));await first;expect(postMessage).toHaveBeenCalledOnce();});
